@baseUrl=http://localhost:3003

# GET request for all users in the database
GET {{baseUrl}}/api/users HTTP/1.1

###
POST {{baseUrl}}/api/users HTTP/1.1
content-type: application/json

{
    "username": "janedoe",
    "name": "Jane Doe",
    "password": "password123"
}